/* B2B home. Claims and copy grounded in the September 2026 owner interview. */
window.CompanionHome = {
  render() {
    return `<div class="business-home">
      <section class="b-hero" aria-labelledby="hero-heading">
        <div class="shell b-hero-grid">
          <div class="b-hero-copy">
            <p class="b-eyebrow"><span class="b-dot" aria-hidden="true"></span> Страхове бюро «Компаньйон»</p>
            <h1 id="hero-heading">Страхування, яке допомагає бізнесу <span>рухатися впевнено.</span></h1>
            <p class="b-intro">Організовуємо тендер, пояснюємо ринок і залишаємося поруч після вибору. Ви бачите варіанти та самі обираєте страхову компанію.</p>
            <div class="b-actions"><a class="b-button" href="#meeting">Домовитися про зустріч <span aria-hidden="true">↗</span></a><a class="b-text-link" href="#solutions">Знайти своє рішення <span aria-hidden="true">↓</span></a></div>
            <p class="b-micro">Безоплатно · Онлайн або особисто в Києві</p>
          </div>
        </div>
        <div class="shell b-metrics" aria-label="Компаньйон у цифрах"><div><strong>97<span>%</span></strong><p>договорів продовжуються</p></div><div><strong>15 678</strong><p>застрахованих людей</p></div><div><strong>70<span>+</span></strong><p>компаній-клієнтів</p></div><p class="b-metrics-note">Партнерство, яке<br>триває після підписання.</p></div>
      </section>
      <section class="b-section" id="solutions" aria-labelledby="solutions-heading"><div class="shell"><div class="b-section-head"><div><p class="b-eyebrow">01 / Напрями</p><h2 id="solutions-heading">Захищаємо те,<br>на чому тримається бізнес.</h2></div><p>Від здоров’я команди до вантажу в дорозі. Для кожного завдання підбираємо програму та організовуємо супровід.</p></div><div class="b-solutions-grid"><article class="b-solution b-solution-dms"><div class="b-solution-top"><span>01</span><span>Люди</span></div><h3>Корпоративне<br>медичне страхування</h3><p>Для команд від 50 людей. Беремо на себе тендер і допомагаємо працівникам користуватися програмою, знімаючи зайве навантаження з HR.</p><a class="b-text-link" href="dms.html">Детальніше про медичне страхування <span aria-hidden="true">↗</span></a></article><article class="b-solution b-solution-logistics"><div class="b-solution-top"><span>02</span><span>Рух</span></div><h3>Логістика</h3><p>Наше давнє профільне спрямування. Страхування вантажів, відповідальності перевізника та складів з урахуванням вашої роботи.</p><a class="b-text-link" href="logistyka.html">Детальніше про логістику <span aria-hidden="true">↗</span></a></article><article class="b-solution b-solution-small"><div class="b-solution-top"><span>03</span><span>Активи</span></div><h3>Майно бізнесу</h3><p>Визначаємо, які ризики важливі для ваших об’єктів, і порівнюємо покриття, ліміти та винятки.</p><a class="b-text-link" href="#meeting" data-interest="Майно бізнесу">Обговорити захист майна <span aria-hidden="true">↗</span></a></article><article class="b-solution b-solution-small"><div class="b-solution-top"><span>04</span><span>Зобов’язання</span></div><h3>Відповідальність бізнесу</h3><p>Допомагаємо підібрати страхування відповідальності перед третіми особами під вашу діяльність та умови договорів.</p><a class="b-text-link" href="#meeting" data-interest="Відповідальність бізнесу">Обговорити відповідальність <span aria-hidden="true">↗</span></a></article></div><div class="b-section-bottom"><span>Потрібне страхування для себе чи родини?</span><a class="b-text-link" href="index.html?page=services">Переглянути всі сервіси <span aria-hidden="true">↗</span></a></div></div></section>
      <section class="b-insights b-section" aria-labelledby="insights-heading"><div class="shell"><div class="b-section-head"><div><p class="b-eyebrow">02 / Актуальне</p><h2 id="insights-heading">Корисне для<br><span>вашого бізнесу.</span></h2></div><p>Коротко пояснюємо страхові рішення, ризики та питання, які виникають у керівників, HR і операційних команд.</p></div><div class="b-insights-grid"><article class="b-insight"><span class="b-insight-type">Порада · 5 хв</span><h3>Як підготувати медичне страхування до нового страхового року</h3><p>Що перевірити в чинній програмі, перш ніж порівнювати пропозиції.</p><a class="b-text-link" href="dms.html">Читати матеріал <span aria-hidden="true">↗</span></a></article><article class="b-insight"><span class="b-insight-type">Логістика · 4 хв</span><h3>П’ять ризиків, які варто врахувати під час перевезень</h3><p>Маршрут, вантаж, відповідальність і документи — короткий список для перевірки.</p><a class="b-text-link" href="logistyka.html">Читати матеріал <span aria-hidden="true">↗</span></a></article><article class="b-insight"><span class="b-insight-type">Підхід · 3 хв</span><h3>Чому брокер порівнює не лише ціну поліса</h3><p>Покриття, ліміти, винятки та сервіс мають значення після підписання договору.</p><a class="b-text-link" href="yak-my-pratsyuyemo.html">Як ми працюємо <span aria-hidden="true">↗</span></a></article></div></div></section>
      <section class="b-process b-section" id="process" aria-labelledby="process-heading"><div class="shell"><div class="b-section-head"><div><p class="b-eyebrow">02 / Як працюємо</p><h2 id="process-heading">Показуємо ринок.<br><span>Рішення завжди за вами.</span></h2></div><p>Щоб ви могли пояснити свій вибір керівництву й команді, ми робимо пропозиції зрозумілими та порівнюваними.</p></div><ol class="b-steps"><li><span class="b-step-no">01</span><h3>Розуміємо вашу задачу</h3><p>Обговорюємо ризики, чинні договори, бюджет і критерії, за якими ви оцінюватимете результат.</p></li><li><span class="b-step-no">02</span><h3>Показуємо ринок</h3><p>Готуємо запит, порівнюємо покриття, винятки, вартість і сервіс. Пояснюємо відмінності між варіантами.</p></li><li><span class="b-step-no">03</span><h3>Супроводжуємо після вибору</h3><p>Допомагаємо запустити програму, працювати зі змінами в договорі та складними страховими питаннями.</p></li></ol></div></section>
      <section class="b-section b-support" aria-labelledby="support-heading"><div class="shell b-support-grid"><div><p class="b-eyebrow">03 / Супровід після підписання</p><h2 id="support-heading">Після вибору<br>не залишаємо вас сам на сам.</h2><p class="b-intro">Для кожної компанії формуємо команду супроводу та зрозумілий порядок роботи. Допомагаємо з документами, змінами в програмі та складними зверненнями.</p><a class="b-text-link" href="index.html?page=about">Познайомитися з командою <span aria-hidden="true">↗</span></a></div><div class="b-service-standards"><p class="b-eyebrow">Ваш формат супроводу</p><div class="b-time"><strong>Команда</strong><p>веде страхові питання та координує потрібні наступні кроки.</p></div><div class="b-time"><strong>Зв’язок</strong><p>телефон, месенджери, email і застосунок — там, де зручно вам і команді.</p></div><p class="b-small">Строки та порядок відповіді для конкретної програми погоджуємо до початку роботи.</p></div></div><div class="shell b-channels"><p>Спілкуємося там, де вам зручно</p><ul><li>Телефон</li><li>Telegram</li><li>Viber</li><li>WhatsApp</li><li>Email</li><li>Застосунок Компаньйон</li></ul></div></section>
      <section class="b-digital b-digital-compact" aria-labelledby="digital-heading"><div class="shell b-digital-grid"><div class="b-app-preview"><img src="presentation-assets/policy.png" alt="Екран Компаньйон: поліс, застраховані особи та покриття програми" width="1290" height="2796" loading="lazy"></div><div class="b-digital-copy"><p class="b-eyebrow">Застосунок для медичного страхування</p><h2 id="digital-heading">Поліс і контакти допомоги — у телефоні працівника.</h2><p class="b-intro">Важлива частина сервісу: людина бачить покриття та швидше розуміє, куди звертатися.</p><a class="b-text-link" href="app.html">Детальніше про застосунок <span aria-hidden="true">↗</span></a></div></div></section>
      <section class="b-section b-meeting" id="meeting" aria-labelledby="meeting-heading"><div class="shell b-meeting-grid"><div><p class="b-eyebrow">Почнемо зі знайомства</p><h2 id="meeting-heading">Розкажіть,<br>що важливо<br><span>вашій компанії.</span></h2><p class="b-intro">Залиште контакти, і ми погодимо зручний час зустрічі. Обговоримо вашу ситуацію, потрібну інформацію та наступні кроки.</p><div class="b-meeting-facts"><p>Безоплатна зустріч</p><p>Онлайн або особисто в Києві</p><p>Для ДМС — з керівником напряму або його заступником</p></div></div><form class="b-meeting-form" id="meeting-form"><label>Ім’я<input type="text" name="name" autocomplete="name" required></label><label>Компанія<input type="text" name="company" autocomplete="organization"></label><label>Телефон або email<input type="text" name="contact" autocomplete="email" required></label><label>Що хочете обговорити?<select name="interest"><option>Корпоративне медичне страхування</option><option>Логістика</option><option>Майно бізнесу</option><option>Відповідальність бізнесу</option><option>Інше</option></select></label><button class="b-button" type="submit">Домовитися про зустріч <span aria-hidden="true">↗</span></button><p class="b-form-note">Натискаючи кнопку, ви погоджуєтесь на обробку персональних даних для зв’язку щодо вашого запиту.</p><p class="b-form-status" id="meeting-status" aria-live="polite"></p></form></div></section>
    </div>`;
  }
};